### ISSUE TITLE
Corpus and database

### ISSUE THREAD

**Issue by oldosamaibraheem11** [osamaibraheem11/CSCI5030#30]
Problem:
Currently we are using a an SQL query that pulls sentences by using "%word%". Anytime it finds the "word" in a sentence it grabs it. We have found a usage bug when running it. The bag is like this if we search for the word "we" as noun it will still come up with sentences. This is happening because "between" is a noun and "we" is in the word between. 

Solution:
We need to use the index table and separate word/speech to two columns word and part_of_speech_id.

**Comment by pnklshh** [comment]
We implemented indexing so the issue is fixed.
